### ISSUE TITLE
Single datapoint series not showing up

### ISSUE THREAD

**Issue by ThinkSalat** [apexcharts/apexcharts.js#1190]
for some reason, replicated in this [codepen](https://codepen.io/TalasNwhas/pen/VwYyqMj?editors=0010), one of the series is not showing up.

If you click the "thought logs" legend item to remove that series, boom, the other series finally shows up.

If you add ONE datapoint to the series with only one datapoint, they start showing up. Very bizarre.

I've been investigating this on my end for hours and can't seem to figure out why it's happening.

**Comment by ThinkSalat** [comment]
Oh and btw, if you remove the first series, the other series just doesn't show up at all.

**Comment by junedchhipa** [comment]
Fixed it.

**Comment by ThinkSalat** [comment]
@junedchhipa https://codepen.io/TalasNwhas/pen/VwYyqMj?editors=0010

I just updated the codepen with the latest apex release and removing the first series ended up making the second series not even show up. Also, the bug persisted on my charts, even though I upgraded to 3.15.0.

There may be something deeper causing this. I noticed that the order of the series seems to affect whether the series shows up correctly or not.
