### ISSUE TITLE
X axis labels are still misaligned

### ISSUE THREAD

**Issue by jimfilippou** [apexcharts/apexcharts.js#167]
## Codepen

https://codepen.io/jimfilippou-the-animator/pen/VEBrwe

## Explanation

I believe this was an older issue which wasn't fixed. I am aware that using `labels: [1,2,3,4,5,6,7,8,9]` will solve the problem, but this is not a solution since the default behavior should align the x-axis properly.
What do you suggest wise man? 💯  

> Removing paddings is not a solution

- What is the behavior you expect?
![untitlee](https://user-images.githubusercontent.com/6877046/47284037-6815ec00-d5ee-11e8-829b-261f22f90973.png)

- What is happening instead?
![untitled](https://user-images.githubusercontent.com/6877046/47284048-72d08100-d5ee-11e8-91cc-7ea7425aeb71.png)

- What error message are you getting?
No error message.

**Comment by junedchhipa** [comment]
Codepen not found

**Comment by jimfilippou** [comment]
@junedchhipa updated... once again 😛

**Comment by junedchhipa** [comment]
If you don't know the number of dataPoints initially, then you can run an additional function after `render()`

```javascript
chart.render()

 chart.updateOptions({
  xaxis: {
    categories: chart.w.globals.labels
  }
})
```

Also, you need to set `xaxis.tickAmount = 'dataPoints'` for it to set the correct tick intervals.
```javascript
xaxis: {
    type: "categories",
    tickAmount: 'dataPoints',
    categories: [],
},
```

Updated [codepen](https://codepen.io/apexcharts/pen/vVabWB)

**Comment by junedchhipa** [comment]
Why can't I view this ticket on GitHub?

**Comment by jimfilippou** [comment]
Github is experiencing a lot of issues today, a lot!  💢

**Comment by jimfilippou** [comment]
The problem is fixed, although this seems more like a 'hacky' way to solve this problem.
Thanks anyway

**Comment by junedchhipa** [comment]
Yeah, for now, it seems hacky way.
I will add this as a default behavior in the next releases for empty categories. Let's keep this ticket open until I fix it

**Comment by jimfilippou** [comment]
@junedchhipa another issue showed up related to this, take a look at this picture
![untitled](https://user-images.githubusercontent.com/6877046/47340745-db2f6900-d6a7-11e8-9002-2958ecd7fe8f.png)

Taking a look at this codepen https://codepen.io/jimfilippou-the-animator/pen/vVzddq
you will see that everything is ok until you see the console which looks like this
![untitled1](https://user-images.githubusercontent.com/6877046/47340995-8809e600-d6a8-11e8-8c03-1cf38ba74fcb.png)

On my end, when it updates the categories with 
```javascript
chart.updateOptions({
        xaxis: {
          categories: this.apexChart.w.globals.labels
        }
      }, false, true);
```

the `w.globals.labels` is 
```
[0.7142857142857142, 1.8117913832199546, 2.909297052154195, 4.006802721088436, 5.104308390022676, 6.201814058956916, 7.299319727891157]
```

so it goes and places that value to the xaxis tooltip, why is this happening?

**Comment by jimfilippou** [comment]
Just to help you out, I have tested the `Math.round()` for a large number of x values and the round function is accurate, take a look https://codepen.io/jimfilippou-the-animator/pen/XxxvZb?editors=1111

**Comment by junedchhipa** [comment]
Thanks for testing with bigger datasets.

Another issue I just noted in your example is that markers show at the top for an empty dataset. That needs to be taken care of as well.

**Comment by jimfilippou** [comment]
Yes, that is also an issue, I was going to open it in another GitHub issue, should I do it now or you prefer to have them both here

**Comment by junedchhipa** [comment]
Please open another, so I can keep track

**Comment by junedchhipa** [comment]
Fixed it in https://github.com/apexcharts/apexcharts.js/commit/7a34f2365394272aeb0661e48a06a38d510eef68

**Comment by jimfilippou** [comment]
Okay, when is the upcoming build?

**Comment by junedchhipa** [comment]
In 1 hour 😁

**Comment by jimfilippou** [comment]
The issue is still here https://codepen.io/jimfilippou-the-animator/pen/zmyKMx?editors=0010

**Comment by junedchhipa** [comment]
@jimfilippou Oops! I totally forgot to test without taking out the `hacky` code which we used previously.
Sorry about that. Also, I noticed - in the docs page, I have mentioned `xaxis.type = 'categories'` when in fact, it has to be `xaxis.type = 'category'`. Fixed the docs and all typos in code also.

Some code refactoring is required now as I did some quick fixes. Will be taken care in the next release.
You'll have to wait for Monday for the next release now 😁 

![screen shot 2018-10-26 at 12 19 17 am](https://user-images.githubusercontent.com/17950663/47523125-f15e4480-d8b4-11e8-94ca-75fc8a94036d.png)
I tested with your latest codepen with my recent fixes - and it's working fine on my side.

Cheers

**Comment by jimfilippou** [comment]
Thanks again! let me know if you need any kind of help 😃

**Comment by jimfilippou** [comment]
@junedchhipa padding is not present
https://codepen.io/jimfilippou-the-animator/pen/XxQKEp?editors=0010

**Comment by junedchhipa** [comment]
I didn't understand the problem. Can you post a screenshot pointing the issue?

**Comment by jimfilippou** [comment]
![sketch 1](https://user-images.githubusercontent.com/6877046/47639506-1cbd8980-db6a-11e8-9d21-fbc1866e6f95.png)

Also the padding is missing from left and right

**Comment by jimfilippou** [comment]
Wait i think i didn't have my cache cleared

**Comment by jimfilippou** [comment]
Yep that was my mistake, solved

**Comment by Shuttler97** [comment]
<img width="653" alt="image" src="https://user-images.githubusercontent.com/33428685/210931776-0b868589-787a-41d5-aa74-c247197900bc.png">

Its still showing wrong aligned, I have upgrade the angular from 10 to 15  and this wrong alingment started coming
Currently I'm using the apex chart 3.36.3

**Comment by Erpiovra87** [comment]
HI! I've a problem with a graph. code here.

```
type: custom:apexcharts-card
apex_config:
  chart:
    stacked: true
graph_span: 7d
series:
  - entity: sensor.enelgrid_daily_import
    type: column
    color: red
    float_precision: 2
    show:
      datalabels: true
    data_generator: |
      const stat_entity = 'sensor:enelgrid_it002e0177172a_consumption';
      var statistics = await hass.callWS({
          type: 'recorder/statistics_during_period',
          start_time: new Date(start).toISOString(),
          end_time: new Date(end).toISOString(),
          statistic_ids: [stat_entity],
          period: "day",
      });
      var stats = statistics[stat_entity];
      var result = [];
      var len = stats.length;
      for (let i = 0; i < len; i++) {
        let stat = stats[i].change;
        result.push([(new Date(stats[i].end).getTime()),stat]);
        }
      return result;
  
    group_by:
      func: sum
      duration: 1d

```

![Image](https://github.com/user-attachments/assets/9eec6e17-f1d6-406c-a69d-13a2395e83cf)

data is not aligned with x axis

![Image](https://github.com/user-attachments/assets/89b972a0-6d5c-4c7c-9a6d-782188d10ccd)
