### ISSUE TITLE
First and last bars are coming out of the bar chart

### ISSUE THREAD

**Issue by shashircciit** [apexcharts/apexcharts.js#1703]
const options = {
    colors: ['#0055fe'],
    width: '100%',
    title: {
        text: '',
        align: 'left',
        margin: 10,
        offsetX: 0,
        offsetY: 0,
        floating: false
    },
    markers: {
        size: 4
    },
    animations: {
        initialAnimation: {
            enabled: false
        }
    },
    stroke: {
        curve: 'smooth',
        width: 2
    },
    xaxis: {
        type: 'datetime',
        labels: {
            datetimeUTC: false,
            datetimeFormatter: {
                year: 'yyyy',
                month: 'MMM \'yy',
                day: 'dd MMM',
                hour: 'HH:mm'
            }
        }
    },
    yaxis: {
        min: 0,
        forceNiceScale: true,
        decimalsInFloat: 2,
        opposite: true,
        title: {
            text: 'Count'
        }
    },
    tooltip: {
        x: {
            format: 'dd MMM HH:mm:ss'
        }
    },
    fill: {
        opacity: [0.85, 0.25],
        gradient: {
            inverseColors: false,
            shade: 'light',
            type: 'vertical',
            opacityFrom: 0.85,
            opacityTo: 0.55
        }
    },
    legend: {
        show: false,
        showForSingleSeries: true
    }
};

export default options;

<img width="1372" alt="Screenshot 2020-06-25 at 10 51 08 AM" src="https://user-images.githubusercontent.com/31244667/85659706-70cb9900-b6d2-11ea-967d-46360cc7234f.png">

**Comment by junedchhipa** [comment]
This was fixed in a recent version of APexCharts.
May I know which version you're using? Can you try updating to the latest version 3.19.3 (as of now)?

**Comment by shashircciit** [comment]
I am using "apexcharts": "^3.18.1".

**Comment by junedchhipa** [comment]
Please try the latest version 3.19.3 and then report if it fixes the issue.

**Comment by shashircciit** [comment]
Hey, still getting the issue. Can you tell me how I can move my first and last bar inside the chart?
<img width="1133" alt="Screenshot 2020-07-03 at 2 19 36 AM" src="https://user-images.githubusercontent.com/31244667/86407966-b04a4480-bcd3-11ea-956b-cb9e7d47b1d0.png">
