### ISSUE TITLE
Negative values appear on y axis while every data-set has positive values

### ISSUE THREAD

**Issue by jimfilippou** [apexcharts/apexcharts.js#181]
## Codepen

https://codepen.io/jimfilippou-the-animator/pen/OBGjJK?editors=0010

## Explanation
Data given is positive, assigning y-axis label with a negative value is not an expected behavior.

- What is the behavior you expect?
![expectation](https://user-images.githubusercontent.com/6877046/47650339-a419f580-db88-11e8-9370-be2e906446ec.png)

- What is happening instead?
![reality](https://user-images.githubusercontent.com/6877046/47650346-aaa86d00-db88-11e8-9990-4ecfaf7755c8.png)

- What error message are you getting?
No error

- Suggestions
If every dataset on series is greater than 0, ignore all negative values on the y-axis.

**Comment by junedchhipa** [comment]
I agree
If no negative values are present, it doesn't make sense to show negative values in the y-axis.

Fixed it

**Comment by C3maLi** [comment]
hi, @junedchhipa 
My question is the same because I wanted to ask my question under this title without opening another title.

Question 1: Although there is no negative value in the data-set, it still shows negative values.
Question 2: How can I hide the tool tip when there are no values ​​in the last two elements of my example? This method is not a problem when chart type and series type are line. Chart type is a line and series type is a column.

The example I made;
[Https://codepen.io/cemali/pen/zgxzzp](url)

thank you in advance.
