### ISSUE TITLE
Website Error: Demo pages throwing errors

### ISSUE THREAD

**Issue by impressivewebs** [apexcharts/apexcharts.js#233]
Seems like the demo pages are down/crashing, I'm getting errors that look like this on most demos I've tried to view:

> Fatal error: Uncaught Error: Call to undefined function bellows() in /home/vectokfz/public_html/wordpress/wp-content/themes/apexcharts/sidebar-gallery.php:13 Stack trace: #0 /home/vectokfz/public_html/wordpress/wp-includes/template.php(690): require()

That's just a snippet of the error, it's much larger than that on the actual page. For example, [this page](https://apexcharts.com/javascript-chart-demos/scatter-charts/basic/).

**Comment by junedchhipa** [comment]
We just moved our website to a different hosting plan and seems the migration caused some compatibility issues.
I have therefore put a notice on the README.md that we are under maintenance mode :)

Thank you for your patience.

**Comment by junedchhipa** [comment]
Fixed the issue

**Comment by impressivewebs** [comment]
Looks like most of them are working except for this one:

https://apexcharts.com/javascript-chart-demos/area-charts/basic/

Which is showing a different WordPress error.

**Comment by junedchhipa** [comment]
Can you share a screenshot or error description?
It works on my side.
Ignore the error in the footer: `Notice: ob_end_flush(): failed to send buffer of zlib output compression (0) in /home/vectokfz/public_html/wordpress/wp-includes/functions.php on line 3786`

**Comment by impressivewebs** [comment]
Hmmm seems to be a caching issue in my browser, because when I view the link incognito, it works. But I still see this in non-incog:

https://i.gyazo.com/c68ee488713add7e5e5291873582e65f.png

And it redirects to:

https://apexcharts.com/wordpress/wp-admin/setup-config.php

I think it's fine now, but at some point that error did show up for me and seems to be cached that way.
