### ISSUE TITLE
Stacked area chart displays data at wrong y-value when there are hidden series

### ISSUE THREAD

**Issue by OllieRadiola** [apexcharts/apexcharts.js#4984]
### Steps to Reproduce

See codepen for example: https://codepen.io/OllieRadiola/pen/JojrpLp

1. Create a stacked area chart with at least 4 series
2. Set one of the series in the middle to hidden (e.g. click on the name in the legend). This seems to only be a problem when hiding the 3rd series and onward
3. The series that comes after the hidden series will display at the wrong y-value. In the provided example, Category D should be a flat line, but the first point is displayed higher than the second.
 
### Expected Behavior

Hidden series should not affect the y-values of subsequent series

### Actual Behavior

In the provided example, it seems like the second point for Category D is displayed too low. It is off by exactly the height of Category B, which is displayed below it.

### Screenshots

When Category C is hidden, Category D is not flat, even though the value is 8 all the way across

![Image](https://github.com/user-attachments/assets/1796448a-6c8a-4ab2-acfa-47fe07a6ac42)

When Category C is not hidden, behaviour is as expected

![Image](https://github.com/user-attachments/assets/853cde34-cd51-4221-a7bc-f15b8337ffc2)

### Reproduction Link

https://codepen.io/OllieRadiola/pen/JojrpLp

**Comment by ND0X** [comment]
Up! 

![Image](https://github.com/user-attachments/assets/ecccb0a5-af09-4c16-b0e9-4b9590886cce)

When Movistar category is hidden

![Image](https://github.com/user-attachments/assets/fed21416-be25-4c96-b7b0-6081f4e42bcb)

**Comment by ND0X** [comment]
Hey, I ran into the same issue and after trying a bunch of things, the only fix that worked for me was sorting the series based on the first x value of each one. Once they were sorted, the chart worked fine and the error was gone.

Just leaving this here in case it helps someone else. Cheers!

**Comment by OllieRadiola** [comment]
> Hey, after trying a bunch of things, the only fix that worked for me was sorting the series based on the first x value of each one. Once they were sorted, the chart worked fine and the error was gone.
> 
> ![Image](https://github.com/user-attachments/assets/487eb1e8-7c79-4ecb-a7f6-3104683840c6)
> 
> Just leaving this here in case it helps someone else. Cheers!

Yeah, this is the same conclusion I came to. Because it seems to only affect hiding the 3rd series and onwards, you can move hidden series to the start. Unfortunately, this is not acceptable for my use-case, so am hoping for a proper fix

**Comment by dpuccion** [comment]
Okay so I digged into the different commits and found this https://github.com/apexcharts/apexcharts.js/commit/7f04fa31e0bb6c80448f94be091a56f8d53f1414

Basically if you set showAlways to true in yaxis in your options the bug will be fixed. I don't know how this can have any effect but it works I guess. But for some reasons now my legend disappears when I collapse all my series.

**Comment by junedchhipa** [comment]
Could we get a fresh reproduction on the current release (6.8.0)?

I tried to reproduce this from the written steps and could not. Building a stacked area chart with 4 and then 5 series and hiding a middle one gave correct stacking every time, including hiding the 3rd series specifically, hiding two adjacent middle series, and hiding the first series. In each case the band after the hidden series sat exactly on the running baseline (the gaps between the rendered lines came out in the expected ratios). The linked CodePen is not reachable from here, so I could not check your exact configuration against the code.

Two possibilities: this was fixed by other work since March 2025, or the trigger is something the steps do not capture.

One specific thing worth checking, because it produces a very similar symptom and **is** still broken on 6.8.0: **do all of your series have the same number of points, with identical x values?** In #4886 a stacked area where one series had 9 points while the others had 12 drew a later series wildly out of position, some of it above the top of the plot. Stacking resolves each series' baseline by data point ordinal rather than by x value, so any series whose x values do not line up with the others gets its baseline from the wrong x. If your data has gaps, that is very likely the same bug, and padding every series onto one shared set of x values (0 or `null` for the gaps) should work around it.

If it still reproduces on 6.8.0 with equal-length, x-aligned series, a CodePen or JSFiddle with the data inline would be very helpful and I will pick it straight up. If it turns out to be the ragged-data case, say so and we can close this as a duplicate of #4886.

**Comment by OllieRadiola** [comment]
@junedchhipa Thanks for looking into this. Not sure why you can't reach my CodePen but I have recreated it as a CodeSandbox which is using 6.8.0 and unfortunately the bug still seems to be there :(
CodeSandbox link: https://codesandbox.io/p/sandbox/apexcharts-demo-forked-79wt7k

<img width="534" height="358" alt="Image" src="https://github.com/user-attachments/assets/5d60c347-9887-47a3-b273-350a3558bd13" />

Here is the full configuration if that is easier:
```js
var options = {
  chart: {
    type: "area",
    stacked: true,
  },
  xaxis: {
    categories: ["a", "b"],
  },
  series: [
    {
      name: "Category A",
      data: [
        { x: "a", y: 7 },
        { x: "b", y: 7 },
      ],
      hidden: false,
    },
    {
      name: "Category B",
      data: [
        { x: "a", y: 5 },
        { x: "b", y: 5 },
      ],
      hidden: false,
    },
    {
      name: "Category C",
      data: [
        { x: "a", y: 4 },
        { x: "b", y: 4 },
      ],
      hidden: true,
    },
    {
      name: "Category D",
      data: [
        { x: "a", y: 8 },
        { x: "b", y: 8 },
      ],
      hidden: false,
    },
  ],
};
```

Hope this helps, let me know if you need anything else

**Comment by junedchhipa** [comment]
@OllieRadiola thank you for the CodeSandbox, that config was the missing piece. **This was fixed in 6.9.0**, one release after the 6.8.0 you tested on.

Reproduced on your exact config, watching series D:

| version | series D, the two points |
|---|---|
| 6.8.0 (what you tested) | `[57.7, 115.3]` ← wrong |
| 6.9.0 / 6.10.0 / current | `[57.7, 57.7]` ✅ |

**Why it happened.** A stacked series walks back to the nearest series that isn't hidden to find its baseline. That walk stepped two positions per hidden series instead of one, so D skipped over B and landed on A: it stacked on 7 units instead of 12. 15/25 of a 288px plot is 115.3px, which is exactly where it drew.

Two things about this worth writing down, since they explain the two and a half years:

- **Only the second point onward was wrong.** The first point of a series doesn't go through that walk at all, so anyone eyeballing the left edge of the chart saw nothing amiss. Your screenshot showing the distortion on the right was the real clue.
- **The commit that fixed it didn't know it was fixing anything.** It was filed as a behaviour-neutral tidy-up of that walk, on the reasoning that a hidden series contributes 0 anyway so any index would give the same answer. That reasoning was wrong (the walk returned the wrong index, not an equivalent one), so this issue was never linked and nobody told you. I've corrected the comment in the source to say the code is load-bearing, and added tests using your config so it can't quietly return.

@dpuccion your finding was closer than it looked: sorting series by their first x value works around a *different* bug with the same symptom, where series of unequal length were stacked by position rather than by x. That one is #4886, and it's just been fixed. If your data has series with differing x values, that's the one that was biting you, and it needs no workaround now.

Closing as fixed in 6.9.0. If you still see anything like this on 6.10.0, please reopen with the config and I'll take another look.
