### ISSUE TITLE
Multiple Y axis cause the axis to crop

### ISSUE THREAD

**Issue by Carniatto** [apexcharts/apexcharts.js#98]
When using multiple Y axis the positioning of the left axis is wrong resulting in copping of the title

![screen shot 2018-09-13 at 17 50 24](https://user-images.githubusercontent.com/1366831/45499941-b2998280-b77d-11e8-8995-54f6b77859f5.png)

**Comment by junedchhipa** [comment]
No, that space shouldn't exist.
Some other users have also reported the same issue when using multiple y-axis - and it's on my roadmap.

**Comment by Carniatto** [comment]
@junedchhipa if you point me in the right direction I can help fix this and open a PR

**Comment by junedchhipa** [comment]
@Carniatto This is fixed in https://github.com/apexcharts/apexcharts.js/commit/8817230d8c94006188e9ee7025ffffe5e1b7d947 
Not merged into master yet, because other related y-axis issues are being processed.

The code for this is located in `src/modules/axes/Yaxis.js` & `src/modules/Dimensions.js`
Thanks for offering help

**Comment by Carniatto** [comment]
@junedchhipa This is still happening in ver 1.5.3

**Comment by junedchhipa** [comment]
Can you please show me your example code for which this is happening?
Maybe I have missed some config - here it works correctly
https://apexcharts.com/javascript-chart-demos/mixed-charts/multiple-yaxis/

**Comment by Carniatto** [comment]
@junedchhipa just tried with the latest version `2.0.6` and the problem persists :(
here's an example: https://stackblitz.com/edit/angular6-apexcharts

I think the problem is when you use formatters for labels it will not consider it

**Comment by junedchhipa** [comment]
Hi @Carniatto 
I will take a look again. Seems like the yaxis labels needs extra attention when there are multiple y-axes.
Re-opening this.

**Comment by Carniatto** [comment]
Hi @junedchhipa this bug is still happening under the same circumstances. Do you mind to check it?

**Comment by saurabhnemade** [comment]
This is still breaking.

<img width="1090" alt="Screenshot 2021-09-01 at 12 19 34 AM" src="https://user-images.githubusercontent.com/17445338/131559273-fe2d583b-d082-4b94-b1a7-933d0facd278.png">

**Comment by saurabhnemade** [comment]
I ended up adding:
```
yaxis: {
     title: { offsetX: 10 }
}
```

but it would be nice if we can fix it permanently without adding offset.
